// Copies contract ABIs from Foundry's build output into the shared package.
// Run after `forge build`: npm run abis
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'contracts', 'out');

const contracts = [
  ['RyokoJourney', 'ryokoJourneyAbi'],
  ['RyokoAccount', 'ryokoAccountAbi'],
  ['TestChogGenesis', 'testChogGenesisAbi'],
  ['TestChogToken', 'testChogTokenAbi'],
];

let body = '// Generated by scripts/export-abis.mjs from contracts/out. Do not edit by hand.\n';
for (const [name, exportName] of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), 'utf8'));
  body += `\nexport const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}

const target = join(root, 'packages', 'shared', 'src', 'abis.ts');
writeFileSync(target, body);
console.log(`Wrote ${contracts.length} ABIs to ${target}`);
